gstbasebackend: Replace single prediction with multiple prediction
RidgeRun/gst-inference pull request #329
Opened 2021-03-03 02:09 UTC by jsalas98

This feature enables the r2inference support for multiple predictions. When received more than 1 output tensor, they will be concatenated into a single 1D array.

2021-03-03 17:26 UTC, michaelgruner requested changes

2021-03-03 17:26 UTC, michaelgruner commented on gst-libs/gst/r2inference/gstbasebackend.cc
> +  *prediction_size = predictions[0]->GetResultSize ();
Do not assume anything. Put everything inside the loop. `g_realloc` works well if the initial memory is `NULL`, precisely for these cases.

2021-03-03 17:26 UTC, michaelgruner commented on gst-libs/gst/r2inference/gstbasebackend.cc
> +  if (1 < num_outputs) {
This will look way cleaner with a single for loop.

2021-03-03 22:48 UTC, michaelgruner approved these changes

2021-03-03 22:48 UTC, michaelgruner commented on gst-libs/gst/r2inference/gstbasebackend.cc
> +    *prediction_data = g_realloc (*prediction_data,
Given that this happens with - potentially - every buffer, I recommend using local variables and finally assigning to the placeholder. I don't know if the compiler is smart enough to avoid the address retrieval on every iteration.

2021-03-03 22:48 UTC, michaelgruner commented on gst-libs/gst/r2inference/gstbasebackend.cc
> +    memcpy(data_offset, predictions[i]->GetResultData(), extra_size);
What is your coding standard? Why isn't the indenter correcting these?

2021-03-03 22:49 UTC, michaelgruner approved these changes
Please attend the last changes before merging.

2021-03-03 23:09 UTC, rrcarlosrodriguez requested changes

2021-03-03 23:09 UTC, rrcarlosrodriguez commented on gst-libs/gst/r2inference/gstbasebackend.cc
>    GST_LOG_OBJECT (self, "Size of prediction %p is %lu",
What if num_outputs is 0? We'll be passing a NULL pointer here and a segfault might happen. Please avoid this log if num_outputs is 0

2021-03-04 00:04 UTC, rrcarlosrodriguez approved these changes

2021-03-08 21:13 UTC, merged