Feature/mobilenetv2ssd support
RidgeRun/gst-inference pull request #330
Opened 2021-03-08 21:18 UTC by jsalas98

2021-03-08 22:20 UTC, rrcarlosrodriguez reviewed
Please make sure we are not leaving any memory behind. A quick valgrind memory test with a basic pipeline should be enough

2021-03-09 17:52 UTC, fasm22 requested changes

2021-03-09 17:52 UTC, fasm22 commented on ext/r2inference/gstmobilenetv2ssd.c
> +    prob = ((gfloat *) (prediction))[i_prob];
Is it possible to cast against gfloat only once? You use this pointer in the rest of this code section multiple times

2021-03-09 17:52 UTC, fasm22 commented on ext/r2inference/gstmobilenetv2ssd.c
> +      gdouble *cur_prob = g_malloc0 (TOTAL_CLASSES * sizeof (gdouble));
When are we releasing this memory?

2021-03-09 22:22 UTC, jsalas98 commented on ext/r2inference/gstmobilenetv2ssd.c
> +      gdouble *cur_prob = g_malloc0 (TOTAL_CLASSES * sizeof (gdouble));
It is released in the postprocess function after it is used, see line 311.

2021-03-10 00:31 UTC, fasm22 approved these changes

2021-03-11 18:12 UTC, michaelgruner requested changes

2021-03-11 18:12 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +    goto out;
We need to free stuff here.

2021-03-11 18:12 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +  probabilities = g_malloc (total_boxes * sizeof (gdouble));
What happens if total boxes is 0?

2021-03-11 18:12 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +    mobilenetv2ssd, gfloat * prediction, gint num_boxes, gint img_width,
I believe our standard is to use `self`

2021-03-11 18:12 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +  probabilities = g_realloc (probabilities, cur_box * sizeof (gdouble));
No need really. Just unnecessary overhead in my opinion.

2021-03-11 18:12 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +      mobilenetv2ssd->prob_thresh = g_value_get_double (value);
Serialize accesses

2021-03-11 18:12 UTC, michaelgruner commented on gst-libs/gst/r2inference/gstinferencepostprocess.c
>  gst_remove_duplicated_boxes (gfloat iou_thresh, BBox * boxes, gint * num_boxes)
Always use double unless you have a special reason not to.

2021-03-15 16:21 UTC, jsalas98 commented on ext/r2inference/gstmobilenetv2ssd.c
> +    mobilenetv2ssd, gfloat * prediction, gint num_boxes, gint img_width,
I checked the other elements and they do not use the self standard.

2021-03-17 00:33 UTC, michaelgruner requested changes

2021-03-17 00:33 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +  pred = (gfloat *) prediction;
Do we really need to drop the `const`?

2021-03-17 00:33 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +  probabilities = g_malloc (total_boxes * sizeof (gdouble));
This is wrong, probabilities is a double pointer. It should be `total_boxes * sizeof (gdouble *)`

2021-03-17 00:33 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +      gdouble *cur_prob = g_malloc0 (TOTAL_CLASSES * sizeof (gdouble));
This size is something we know from outside. When dealing with allocations, keep symmetry. Try not to alloc here and free outside. It's better to alloc and free outside, and fill here.

2021-03-23 19:53 UTC, michaelgruner approved these changes

2021-03-23 20:56 UTC, merged