Feature/add rosetta model support
RidgeRun/gst-inference pull request #340
Opened 2021-11-22 01:30 UTC by Edjchg

Add the support for Rosetta model for character recognition.

2021-11-22 15:22 UTC, lleon95 requested changes
Please, check the indentation and code style guide:

https://developer.ridgerun.com/wiki/index.php?title=RidgeRun_Developer_Manual/Coding_Styles/C

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  int max_indexes[26];
Could you parametrise the `26` through a macro? This avoid magic numbers

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  GST_LOG_OBJECT (vi, "The prhase is %s", output);
Typo: `phrase`

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +      GST_INFO_OBJECT (vi, "Output tensor %i = %f", i, row[i]);
Please, use another qualifier like `GST_DEBUG_OBJECT` instead to avoid polluting the message log

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  GST_INFO_OBJECT (vi, "Predicting...");
Same here. You can use either `DEBUG` or LOG as other elements like `gstinceptionv2`

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +
Remove unneeded spaces

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +
Remove unneeded space

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  GST_LOG_OBJECT (vi, "The end");
I think `the end` may not be suitable. Perhaps "Prediction done"?

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  printf ("The phrase is: %s\n", output);
Do not use `printf`. The LOG object may be enough for this case

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  free (output);
Modify this accordingly. For freeing `g_strnfill`, use `g_free()`

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +
Remove unneeded space

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +gst_rosetta_postprocess (GstVideoInference * vi,
I am a bit concerned about the use of the GstInference methods. If you check other elements, you may check that GstInference provide functions for printing, building the metadata blocks, and so on. Please, take them as a reference:

* https://github.com/RidgeRun/gst-inference/blob/master/ext/r2inference/gstinceptionv2.c#L238
* https://github.com/RidgeRun/gst-inference/blob/master/ext/r2inference/gsttinyyolov3.c#L289

The prediction class is declared here:
https://github.com/RidgeRun/gst-inference/blob/a1428f86f967a7e21ea715a4d055d3bdffe3eb9b/gst-libs/gst/r2inference/gstinferenceprediction.h

and defined here:
https://github.com/RidgeRun/gst-inference/blob/55cad49398398f1fcc424f76244e65585c7cd8f4/gst-libs/gst/r2inference/gstinferenceprediction.c

2021-11-22 15:22 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  char *output = NULL;
Same comment about `glib` types

2021-11-22 15:22 UTC, lleon95 commented on gst-libs/gst/r2inference/gstinferencepreprocess.h
> + * \brief Normalize the image to match the Rosetta input tensor requirements.
Please, do not introduce `Rosetta` into generic modules.  Let's keep it as:

"Normalize grayscale image the image within a given mean and offset"

2021-11-22 15:22 UTC, lleon95 commented on gst-libs/gst/r2inference/gstinferencepreprocess.c
> +  gint i, j, pixel_stride, width, height;
Initialise variables

2021-11-22 15:22 UTC, lleon95 commented on gst-libs/gst/r2inference/gstinferencepreprocess.c
> +                  j)] / mean - offset);
Let's compute the reciprocal of the mean and change the division for performance purposes.

For instance:

```c
  rcp_mean = 1. / mean; /*  rcp_mean is a double */

  for (i = 0; i < height; ++i) {
    for (j = 0; j < width; ++j) {

      ((gfloat *) outframe->data[0])[(i * width + j)] =
          (((guchar *) inframe->data[0])[(i * pixel_stride +
                  j)] * rcp_mean - offset);
```

2021-11-22 15:22 UTC, jsalas98 requested changes

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  "height=32, "							\
Align this `\ `with the others.

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  return;
This return is unnecessary.

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +gst_rosetta_set_property (GObject * object, guint property_id,
Remove this set/get_property functions since they are not doing anything special. The less code, the less errors to debug later.

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +
Remove extra new line

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  float largest = row[0];
Prefer glib types when writing Gstreamer code (i.e gfloat, gint, gchar, etc)

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +    if (maxIndixes[i] != 0 && !(i > 0 && (maxIndixes[i - 1] == maxIndixes[i]))) {
Typo maxIndixes -> maxIndexes

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  char chars[37] =
Use the macros you defined, instead of magic numbers

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  int max_indexes[26];
Use the macros you defined, instead of magic numbers

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  GST_INFO_OBJECT (rosetta, "Rosetta Postprocess");
Remove this duplicated debug.

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  GST_INFO_OBJECT (vi, "Predicting...");
These function is executed per every buffer, so it should have a debug category of LOG, instead of INFO. Check the log levels here https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html?gi-language=c

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +
Remove extra newline

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  GST_LOG_OBJECT (vi, "The end");
Add a more meaningful message here or remove it.

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  printf ("The phrase is: %s\n", output);
You shouldn't be printing directly to standard output, it is enough with the log message.

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +  GST_LOG_OBJECT (vi, "The prhase is %s", output);
Typo prhase -> phrase

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +      (char *) malloc (sizeof (char) * (MODEL_OUTPUT_ROWS) + 1);
Prefer glib functions for memory allocation too (i.e g_malloc0, g_free, etc)

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +
Remove this line

2021-11-22 15:22 UTC, jsalas98 commented on ext/r2inference/gstrosetta.c
> +static gboolean
These start/stop functions are not doing anything special either, so remove them.

2021-11-22 15:22 UTC, jsalas98 commented on gst-libs/gst/r2inference/gstinferencepreprocess.c
> +static void gst_apply_gray_normalization (GstVideoFrame * inframe,
Check indentation.

2021-11-22 15:22 UTC, jsalas98 commented on gst-libs/gst/r2inference/gstinferencepreprocess.c
> +  gint i, j, pixel_stride, width, height;
Initialize these variables.

2021-11-22 15:24 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +    if (maxIndixes[i] != 0 && !(i > 0 && (maxIndixes[i - 1] == maxIndixes[i]))) {
It should be max_indices according to our style guide.

> indices is the plural form of index

2021-11-30 14:20 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +  "height=32, "							\
Still missing

2021-11-30 14:21 UTC, lleon95 commented on gst-libs/gst/r2inference/gstinferencepreprocess.c
> +static void gst_apply_gray_normalization (GstVideoFrame * inframe,
Still missing. GStreamer indentation is with `gst-indent`

2021-11-30 14:21 UTC, lleon95 commented on gst-libs/gst/r2inference/gstinferencepreprocess.c
> +
remove this space

2021-11-30 14:23 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +#include "stdio.h"
still missing

2021-11-30 14:24 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +    //if the actual max index is equal from the previous one.
Use a comment style only. GStreamer uses ANSI-C `/* */`

2021-11-30 14:25 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +static gboolean
still missing

2021-11-30 14:26 UTC, lleon95 commented on ext/r2inference/gstrosetta.c
> +      "   Luis Leon <luis.leon@ridgerun.com>\n\t\t\t");
Remove the last `\n\t\t\t` and the spaces at the beginning

2021-12-01 00:17 UTC, lleon95 approved these changes

2021-12-01 00:20 UTC, merged