update available caps for mobilenetv2ssd
RidgeRun/gst-inference pull request #345
Opened 2022-08-30 21:39 UTC by greivinbm

add another caps (width, height) to mobilenetv2ssd element

2022-08-30 21:43 UTC, michaelgruner requested changes

2022-08-30 21:43 UTC, michaelgruner commented on ext/r2inference/gstmobilenetv2ssd.c
> +  "height={ 300, 192 }, "							\
please align the line breaks. You might need to replace your tabs with spaces to get it right.

2022-08-31 14:56 UTC, robertogs2 commented on ext/r2inference/gstmobilenetv2ssd.c
> +  "height={ 300, 192 }, "							\
I still see an issue with the line breaks, you have a mixture of tabs and spaces:

![image](https://user-images.githubusercontent.com/22207159/187710088-628f3144-7718-4604-8ba6-3e226d937cf3.png)

(dots are spaces and arrows are tabs).

2022-08-31 16:50 UTC, michaelgruner approved these changes

2022-08-31 16:58 UTC, merged